name: universal
favicon: null
layout_spectrum: 0.72811
typography_spectrum: 0.13742
title: Universal Industries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#f8be38'
    - '#3c2808'
    - '#815816'
  brandStrength: 0.25
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
