name: universal
favicon: null
layout_spectrum: 0.8137
typography_spectrum: 0.13742
title: Universal Industries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080510'
    - '#e8a5f9'
    - '#581b59'
    - '#3f5e89'
    - '#838089'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
